name: Release

on:
  push:
    tags:
    - "v*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.25

    - name: Build linux amd64
      run: env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o akavefs-linux-amd64 -v && ln -s akavefs-linux-amd64 akavefs

    - name: Build linux arm64
      run: env CGO_ENABLED=0 GOARCH=arm64 go build -o akavefs-linux-arm64 -v

    - name: Build Mac amd64
      run: env CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o akavefs-mac-amd64 -v

    - name: Build Mac arm64
      run: env CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o akavefs-mac-arm64 -v

    - name: Build Windows x64
      run: env CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o akavefs-win-x64.exe -v

    - name: Build tests
      run: go test -c github.com/yandex-cloud/geesefs/core -o akavefs-tests-linux-amd64

    - name: Publish to S3
      run: |
        sudo apt-get -y install s3cmd
        s3cmd ${{secrets.S3CMD}} put akavefs-linux-amd64 s3://${{secrets.S3BUCKET}}/akavefs-linux-amd64
        s3cmd ${{secrets.S3CMD}} put akavefs-linux-arm64 s3://${{secrets.S3BUCKET}}/akavefs-linux-arm64
        s3cmd ${{secrets.S3CMD}} put akavefs-mac-amd64 s3://${{secrets.S3BUCKET}}/akavefs-mac-amd64
        s3cmd ${{secrets.S3CMD}} put akavefs-mac-arm64 s3://${{secrets.S3BUCKET}}/akavefs-mac-arm64
        s3cmd ${{secrets.S3CMD}} put akavefs-win-x64.exe s3://${{secrets.S3BUCKET}}/akavefs-win-x64.exe
        s3cmd ${{secrets.S3CMD}} put akavefs-tests-linux-amd64 s3://${{secrets.S3BUCKET}}/akavefs-tests-linux-amd64
        s3cmd ${{secrets.S3CMD}} put akavefs-linux-amd64 s3://${{secrets.S3BUCKET}}/${GITHUB_REF/refs\/tags\/v/}/akavefs-linux-amd64
        s3cmd ${{secrets.S3CMD}} put akavefs-linux-arm64 s3://${{secrets.S3BUCKET}}/${GITHUB_REF/refs\/tags\/v/}/akavefs-linux-arm64
        s3cmd ${{secrets.S3CMD}} put akavefs-mac-amd64 s3://${{secrets.S3BUCKET}}/${GITHUB_REF/refs\/tags\/v/}/akavefs-mac-amd64
        s3cmd ${{secrets.S3CMD}} put akavefs-mac-arm64 s3://${{secrets.S3BUCKET}}/${GITHUB_REF/refs\/tags\/v/}/akavefs-mac-arm64
        s3cmd ${{secrets.S3CMD}} put akavefs-win-x64.exe s3://${{secrets.S3BUCKET}}/${GITHUB_REF/refs\/tags\/v/}/akavefs-win-x64.exe
        s3cmd ${{secrets.S3CMD}} put akavefs-tests-linux-amd64 s3://${{secrets.S3BUCKET}}/${GITHUB_REF/refs\/tags\/v/}/akavefs-tests-linux-amd64

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          akavefs-linux-amd64
          akavefs-linux-arm64
          akavefs-mac-amd64
          akavefs-mac-arm64
          akavefs-win-x64.exe
